---
spring:
  profiles: Standalone
  application:
    name: webfront

server:
  port: 20001

# 自定义配置
timeMisroService:
  server: http://microservice-time
  v1:
    uri: http://microservice-time/time/v1

# Ribbon 负载均衡配置
# 取消eureka 依赖
ribbon:
  eureka:
    enabled: false
# microservice-time 相对于虚拟主机，RestTemplate 必须使用microservice-time 访问 才能走复杂均衡策略
microservice-time:
  ribbon:
    # LoadBalancer
    NFLoadBalancerClassName:  com.netflix.loadbalancer.DynamicServerListLoadBalancer
    # 由于禁用了Ribbon Eureka获取服务ip端口，需要手动提供
    listOfServers: 127.0.0.1:10001,127.0.0.1:10002
    # 负载均衡策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    # ping策略
    NFLoadBalancerPingClassName: com.netflix.loadbalancer.NoOpPing

---
spring:
  profiles: Instance1
  application:
    name: webfront

server:
  port: 20001

# 自定义配置
timeMisroService:
  server: http://localhost:10001
  v1:
    uri: http://microservice-time/time/v1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:50001/eureka/,http://localhost:50002/eureka/,http://localhost:50003/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
    # 所属集群，提交使用
    metadata-map:
      cluster: webfront-cluster

# 启动 feign hystrix 支持
feign:
  hystrix:
    enabled: false

# Hystrix stream
management:
  endpoints:
    web:
      exposure:
        include: ["*"]
  endpoint:
    health:
      show-details: always

hystrix:
  # Hystrix 命令配置
  command:
    # 命令默认配置
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100
      circuitBreaker:
        requestVolumeThreshold: 1
        errorThresholdPercentage: 50
        sleepWindowInMilliseconds: 10000
    # 指定命令配置，这里使用的是 @HystrixCommand 中的   commandKey = "microservice-time.now"（除非公共，一般不建议在配置文件中统一配置）
    microservice-time.now:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100
      circuitBreaker:
        requestVolumeThreshold: 1
        errorThresholdPercentage: 50
        sleepWindowInMilliseconds: 10000
  # Hystrix  线程池配置
  threadpool:
    # 线程池默认配置
    default:
      coreSize: 1
      maxQueueSize: 1
      metrics:
        rollingStats:
          timeInMilliseconds: 10000
          numBuckets: 1
    # 指定命令线程池配置，这里使用的是 @HystrixCommand 中的   groupKey = "microservice-time",
    microservice-time:
      coreSize: 5
      maxQueueSize: 5
      metrics:
        rollingStats:
          timeInMilliseconds: 10000
          numBuckets: 1
---
spring:
  profiles: Instance2
  application:
    name: webfront

server:
  port: 20002


# 自定义配置
timeMisroService:
  server: http://localhost:10001
  v1:
    uri: http://microservice-time/time/v1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:50001/eureka/,http://localhost:50002/eureka/,http://localhost:50003/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
    metadata-map:
      cluster: webfront-cluster

# 启动 feign hystrix 支持
feign:
  hystrix:
    enabled: false

# Hystrix stream
management:
  endpoints:
    web:
      exposure:
        include: ["*"]
  endpoint:
    health:
      show-details: always