server:
  port: 60011

spring:
  application:
    name: turbine-server-standalone

# Eureka 集成方式
turbine:
  # appConfig 值为Eureka ServiceId 列表，用于 turbine找到 instance
  appConfig: webfront
  clusterNameExpression: metadata['cluster']
  # 集群参数，指定要监控的集群
  aggregator:
    clusterConfig: ["webfront-cluster"]

# 依赖 Eureka 进行配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:50001/eureka/,http://localhost:50002/eureka/,http://localhost:50003/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true

# actuator
management:
  endpoints:
    web:
      exposure:
        include: ["*"]
  endpoint:
    health:
      show-details: always
